### ISSUE TITLE
Remaining Budgets

### ISSUE THREAD

**Issue by filebound** [TheAlphaSchoolSystemPTYLTD/accounts-payable-integration#22]
Is it possible to expose the remaining budget for GL Codes in addition to the total budget amounts that are currently available?

**Comment by ricardorusson** [comment]
TASS will be providing a new API/Endpoint for budget information. I will leave this issue open until the new documentation has been published.

**Comment by scottetass** [comment]
Hi,

Endpoint getCOA returns budget information, but unfortunately it does not return remaining budget amounts. At this stage there are no plans for including remaining budget amounts due to outstanding commitments in this area within the TASS product needing to be done first.

We will keep it on our radar for potential inclusion once preceding changes in TASS have been completed.

Thanks, Scott
